openapi: 3.0.3
info:
  title: authentication-service
  description: Authentication Service
  version: 1.0.0
servers:
  - url: http://localhost:8082
    description: Development server
paths:
  /:
    get:
      responses:
        200:
          description: OK
  /api/v1/authentication-service/public/token:
    $ref: 'endpoint/LoginUser.yml'
  /api/v1/authentication-service/internal/register:
    $ref: 'endpoint/User.yml'
